### ISSUE TITLE
Déconnexion à l'ouverture d'une page dans un nouvel onglet (Inpact-Hardware)

### ISSUE THREAD

**Issue by florian-s-code** [NextINpact/InpactHardware#1]
Navigateur : Firefox Nightly (66.0a1) avec blocage de pub + HttpsEverywhere + Ublock Origin

Après connexion sur un page du site quelconque, lorsque je fais "Ouvrir dans un nouvel onglet" sur un lien, cette nouvelle page s'ouvre en mode non connecté.
Il faut que je me reconnecte. La page initiale reste en mode connecté.

Étapes pour reproduire:
- Ouvrir https://www.inpact-hardware.com/
- Se connecter
- Ouvrir un article dans un nouvel onglet

Le navigateur bloque certaines requêtes, ce qui pourrait causer le problème. Ci-joint une copie des messages d'erreur dans la console de Firefox.
[log_js_inpacthardware.txt](https://github.com/NextINpact/nxiv6/files/2777127/log_js_inpacthardware.txt)

**Comment by pehadavid** [comment]
C'est corrigé depuis la build déployée mi-mai ;)

**Comment by Borgnasse** [comment]
Personnellement j'ai toujours le problème au jour d'aujourd'hui.

Système : http://supportdetails.net/QYVXBBPK
Extensions Firefox : uBlock Origin, uMAtrix, Disconnect

**Comment by pehadavid** [comment]
@Borgnasse on ne reproduit pas de notre coté. Qu'est-ce que ça donne sur un navigateur alternatif ? avec la navigation privée de Firefox ?

**Comment by Borgnasse** [comment]
Le fonctionnement est correct depuis Safari en mode normal, Chrome en mode normal ou privé, mais pas Firefox. J'investigue pour voir si ça ne peut pas venir de mes extensions.

[EDIT] Sur Firefox en mode privé avec toutes mes extensions désactivées le problème persiste :-/

**Comment by pehadavid** [comment]
Merci pour le retour, ça me prendre un peu de temps car je n'ai ce souci ni sur linux, si sur windows (firefox à jour). ça semble être cantonné a Firefox Mac, je vais voir si j'ai possibilité d'avoir un test équivalent.
