### ISSUE TITLE
Remplissage auto du login / mot de passe ne remplit qu'un champ sur les deux

### ISSUE THREAD

**Issue by Borgnasse** [NextINpact/InpactHardware#11]
(J'utilise Dashlane comme gestionnaire de mots de passe)

=> Lorsque je clique sur "Connexion" sur l'écran titre https://www.inpact-hardware.com/ 
=> et que je veux utiliser mon gestionnaire de mot de passe pour remplir les champs "Pseudo ou email" et "mot de passe"
=> Alors le gestionnaire ne remplit que le champ à partir duquel j'ai demandé le remplissage auto, mais pas l'autre champ
=> Il faut que je redemande un remplissage auto à partir de l'autre champ pour pouvoir enfin me connecter

Je comprendrais que ce bug puisse être dû au gestionnaire de mot de passe lui-même, mais je rencontre cette problématique __uniquement__ sur Inpact Hardware.

Système : http://supportdetails.net/QYVXBBPK
Extensions : uBlock Origin, uMatrix, Disconnect, Dashlane

**Comment by CyberSinh** [comment]
Pour ma part, avec Chrome (et uBlock Origin), je constate que la saisie automatique de ces champs ne fonctionne pas : ni le login, ni le mot de passe (on ne me propose même pas de l'enregistrer d'ailleurs). Pas très pratique lorsque l'on a un mot de passe compliqué à retenir, ce qui est une bonne pratique de SSI.

Combiné avec le problème des déconnexions intempestives (dont je comprends qu'il serait réglé), l'abonné que je suis est parfois découragé de poursuivre la lecture des articles.

Je n'ai aucun problème de ce type avec Next INpact.

**Comment by BenjaminINpact** [comment]
Hello, 
Concernant la mémorisation des identifiants nous avons ajouté un ticket pour le proposer. Nous allons regarder le comportement pour le remplissage auto.

**Comment by Djiko** [comment]
Un truc si vous rencontrez ce problème avec KeepassXC (sur INpact Hardware et NextINpact). Le fonctionnement suivant résout le problème de mon côté : clic droit sur le champ Pseudo > KeepassXC > Remplir le nom d'utilisateur et le mot de passe. Les 2 champs sont alors correctement peuplés.
