### ISSUE TITLE
[CSS] Breakpoint manquant pour le champ de recherche

### ISSUE THREAD

**Issue by ChrisRast** [NextINpact/InpactHardware#13]
Hello,
Exemple de recherche: https://www.inpact-hardware.com/recherche;q=asus

Le champ de recherche n'est pas redimensionné quand on passe entre les breakpoint de 1025px et 1300px de la media query. Il a une largeur fixe qui n'est pas surchargée.

Je vous donne même le sélecteur 😋 `.search-text[_ngcontent-inpacthardware-c16]`.

<img width="1244" alt="Screenshot 2020-04-16 at 10 47 01" src="https://user-images.githubusercontent.com/4668052/79435987-9c464f00-7fd0-11ea-87ab-33bb3c3f83fd.png">

Ce problème arrive quel que soit le navigateur et l'OS mais en version desktop évidemment.

Bonne chasse !

**Comment by BenjaminINpact** [comment]
Hello, 
Merci de ce retour ! je vais regarder ça.
