### ISSUE TITLE
Article de la une non-visible

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/InpactHardware#17]
Bonjour,

Depuis firefox sur android (voir détail plus bas), quand l'option "Masquer la une" est désactivé je ne voie pas les derniers articles en une. Alors que si j'active cette option, l'article apparait dans le flux d'activité

# "Masquer la une" désactivé :
Voici l'état de mes options :
![Screenshot_20200921-154126](https://user-images.githubusercontent.com/36851093/93774231-521d6580-fc21-11ea-9a91-963aca7eb5c0.jpg)
Avec le rendu sur la page d'accueil :
![Screenshot_20200921-154131](https://user-images.githubusercontent.com/36851093/93774232-52b5fc00-fc21-11ea-8b17-1e1afd663e45.jpg)

# "Masquer la une" activé :
Voici l'état de mes options :
![Screenshot_20200921-154137](https://user-images.githubusercontent.com/36851093/93774236-534e9280-fc21-11ea-8733-262570ff9135.jpg)
Avec le rendu sur la page d'accueil :
![Screenshot_20200921-154142](https://user-images.githubusercontent.com/36851093/93774225-50ec3880-fc21-11ea-91be-e46583729971.jpg)

# Détails de la configuration :
* Navigateur : Firefox 80
* Javascript : Activé
* User Agent : Mozilla/5.0 (Android 10; Mobile; rv:80.0) Gecko/80.0 Firefox/80.0

**Comment by BenjaminINpact** [comment]
Merci du retour, cela avait été corrigé.
