### ISSUE TITLE
INpact Hardware : 404 sur les pseudos des commentaires

### ISSUE THREAD

**Issue by 4E71-NOP** [NextINpact/InpactHardware#19]
En voulant répondre sur une news je me rend compte que les commentaires sont fermés (ancien). Et bon je voulais remercier le gars (comme je ne suis pas un salopard a moitié) en MP.  En cliquant sur son pseudo, je tombe sur une 404. Et ça le fait pour tout le monde.

Ex: https://www.inpact-hardware.com/inpactien/1

Si vous êtes déjà au courant on passe à la suite.

**Comment by ghost** [comment]
Je n'ai reproduit ce bug n'est que sur "INpact Hardware". Sur Next INpact cela fonctionne bien.

**Comment by bastien-c** [comment]
le problème est solutionné, il y a désormais une page inpactien au clic du pseudo d'un utilisateur dans les commentaires sur INpact Hardware comme sur NextInpact.
