### ISSUE TITLE
Bandeau accès article payant pour non abonnés

### ISSUE THREAD

**Issue by DanLo-peratingSystem** [NextINpact/InpactHardware#21]
Hello,

Je viens de remarquer (non vérifié sur NXi) qu'en fin d'article, le bandeau me propose de me connecter pour accéder aux articles payants.... Alors que je suis déjà connecté.

La 1ere des 3 options du bandeau devrait être retirée du coup dans cette situation.

![Screenshot_20210520-132534](https://user-images.githubusercontent.com/11614445/118971222-71ff5780-b96f-11eb-9b5f-575dcbf048bb.png)

**Comment by BenjaminINpact** [comment]
Hello DanLo, 
Merci du retour, effectivement c'est le cas sur les 2 sites, on va corriger ça ;)

**Comment by BenjaminINpact** [comment]
Hello, 
C'est corrigé depuis lundi ;)
