### ISSUE TITLE
Cadre contenant auteur et date de publication non-affiché

### ISSUE THREAD

**Issue by DuchkPy** [NextINpact/InpactHardware#23]
Bonjour, sur cet article : https://www.inpact-hardware.com/article/2838/3-nuances-dorbi-quelles-performances-pour-differents-modeles-wi-fi-6 le cadre affichant l'auteur de l'article ainsi que sa date de publication n'est pas affiché.
J'ai testé sur plusieurs navigateur et plusieurs OS (PC et mobile).

Voici ce qui est affiché :
![image](https://user-images.githubusercontent.com/36851093/147851849-81364471-c67b-4bad-b17c-40f27d289547.png)

**Comment by pehadavid** [comment]
Hello,

Ce n'est pas un bug, mais un oubli, j'ai remonté a la rédac' et c'est désormais corrigé ;)

**Comment by DuchkPy** [comment]
Bonjour,

Une petite évolution du code pour éviter cet oubli ?
Par exemple en bloquant la publication avec une alerte si l'information n'a pas été renseigné. Ou en mettant à défaut "la rédaction"
