### ISSUE TITLE
Commentaires avec un ! en fond rouge

### ISSUE THREAD

**Issue by kihsu** [NextINpact/InpactHardware#5]
Bonjour,
la partie des commentaires contient une erreur, sur PC quand on rapetisse en largeur la fenêtre.
![fenêtre](https://user-images.githubusercontent.com/48483017/54205276-58803c80-44d6-11e9-9900-a2189e7f1bdf.png)
Quand on la ragrandi, le bug disparaît (le responsive design change la page web).

Apparemment le bug n'est présent que quand je suis connecté, testé avec ou sans ABP et sous chrome 72 et Opera 58.

Windows 10 version 1809

edit : apparemment en cherchant dans le code du site ça a l'air d’être:
`<div _ngcontent-c31="" class="button-mobile red"><i _ngcontent-c31="" class="fas fa-exclamation-triangle" title="Signaler ce commentaire"></i></div>`

Mais je ne peux pas cliquer dessus et il n'y a aucune tooltip qui s'affiche.

De plus la petite bande verticale verte (bien visible avec son icone si je supprime la ligne sus nommée du rendu de la page) est aussi sans tooltip et je ne peux pas non plus cliquer dessus:
![citer](https://user-images.githubusercontent.com/48483017/54207195-08a37480-44da-11e9-8855-8473eed899ca.png)

`<div _ngcontent-c31="" class="button-mobile green"><i _ngcontent-c31="" class="fas fa-quote-right" title="Citer"></i></div>`

**Comment by BenjaminINpact** [comment]
Bonjour, 
Merci pour votre retour, nous avons corrigé le problème d'affichage. 
Bonne journée, 
L'équipe de Next INpact
