### ISSUE TITLE
Commentaires ne correspondants pas à l'actualité affichée

### ISSUE THREAD

**Issue by Aarklendoia** [NextINpact/InpactHardware#6]
Si on est en train de consulter les commentaires d'une actualité et que via la colonne de droite on clique directement pour afficher les commentaires non-lus d'une autre actualité, il arrive que ces derniers se chargent sous l'actualité en cours au lieu que l'actualité concernée s'affiche d'abord, puis les commentaires associés.
Du coup, on se retrouve avec des commentaires sans rapport avec l'actualité affichée !

**Comment by pehadavid** [comment]
sous quel navigateur ? on ne reproduit pas de notre coté (et même a la limite, si t'as un dump de la console au moment ou ça arrive, ça nous arrange ;))

**Comment by Aarklendoia** [comment]
Je l’ai eu 2 fois sous Edge (Windows 1810). Je vais essayer de le reproduire, ça n’arrive pas à tous les coups. D’ailleurs, je l’ai déjà eu une fois sur NXI aussi.


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Pierre-Alain David <notifications@github.com>
Envoyé : Monday, March 18, 2019 1:54:23 PM
À : NextINpact/InpactHardware
Cc : Aarklendoia; Author
Objet : Re: [NextINpact/InpactHardware] Commentaires ne correspondants pas à l'actualité affichée (#6)


sous quel navigateur ? on ne reproduit pas de notre coté (et même a la limite, si t'as un dump de la console au moment ou ça arrive, ça nous arrange ;))

**Comment by Aarklendoia** [comment]
Je viens de le reproduire. Je pense que ça vient de la lenteur du chargement. En effet, j'étais sur la news "Samsung produit ses puces de LPDDR4X de 12 Go en masse", avec 2 commentaires. J'ai cliqué sur le "16" de la news "À IT Partners 2019, de plus en plus de machines compactes ou portables pour professionnels" dans la colonne de droite.

J'ai d'abord eu une barre de chargement très longtemps (20 à 30s). Puis l'actualité s'est affichée avec les 2 commentaires de la news précédente. J'ai attendu bien 30s et là soudain la page s'est rechargée une seconde fois avec les bons commentaires.

La console donne :

`HTML1300: Une navigation s’est produite.
search (1,1)

HTML1503: La balise de début est inattendue.
search (3,15)

3HTML1416: Caractère inattendu à la fin d’un commentaire ; attendu « --> ».
search (27,11159)

BHX19001: La demande de https://www.bing.com/fd/ls/l?IG=0D584481449A42C49B107066701E75E9&Type=Event.CPT&DATA={%22pp%22:{%22S%22:%22L%22,%22FC%22:30,%22BC%22:181,%22SE%22:-1,%22TC%22:-1,%22H%22:225,%22BP%22:248,%22CT%22:252,%22IL%22:2},%22ad%22:[-1,-1,1904,967,1904,1721,0]}&P=SERP&DA=DUB02 est annulée par l’extension EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62.

SEC7131: La sécurité d’un IFrame en mode Bac à sable (sandbox) est potentiellement compromise en autorisant l’accès au script et de même origine.

BHX19001: La demande de https://www.bing.com/fd/ls/lsp.aspx est annulée par l’extension EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62.

BHX19001: La demande de https://www.bing.com/fd/ls/GLinkPing.aspx?IG=0D584481449A42C49B107066701E75E9&&ID=SERP,5130.1&url=https%3A%2F%2Fwww.inpact-hardware.com%2F est annulée par l’extension EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62.

HTML1300: Une navigation s’est produite.
www.inpact-hardware.com (1,1)

BHX19001: La demande de https://www.bing.com/fd/ls/lsp.aspx est annulée par l’extension EdgeExtension_37833NikRollsuBlockOrigin_f8jsg5mm64m62.

Running in the browser with appId=inpacthardware

[2019-03-18T14:37:38.198Z] Information: WebSocket connected to wss://api-v1.inpact-hardware.com/notifications?signalrtoken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFZHRlY2giLCJqdGkiOiI0MjRjZTZkNy1iMDk5LTRjN2QtYTE5ZS1jZDc1NDg0ZWVjMjkiLCJlbWFpbCI6Im5leHRpbnBhY3RAb3V0bG9vay5mciIsIkF2YXRhclVyaSI6Imh0dHBzOi8vY2RuMi5uZXh0aW5wYWN0LmNvbS9pbWFnZXMvYmQvYXZhdGFyLzEwNTg1OC0yMDE2MDgwNzA5MTMzMjMxMS5qcGc_dj02MzYwNjE1ODAxMjMxMTc0NTciLCJVc2VySUQiOiIxMDU4NTgiLCJBYm9ubmVtZW50IjoiXCIyMDIwLTAxLTMxVDA3OjQzOjQxXCIiLCJMb2dpbiI6IkVkdGVjaCIsIkRhdGVDcmVhdGVkIjoiMDMvMTgvMjAxOSAxMToxNjowMCIsIk5iQ29tbWVudHNQZXJQYWdlIjoiMTAiLCJSYW5rIjoiQmFzaWMiLCJleHAiOjE1NTM1MTI1NjAsImlzcyI6IklOcGFjdE1lZGlhZ3JvdXAiLCJhdWQiOiJJTnBhY3RNZWRpYWdyb3VwIn0.FEGFRNYfdisZKy7mEVP6oIT6wAFA6ieo8XoxSx-hBIA&id=r_qxR5qJfg20DUbwNzyrqQ.

SEC7137: [Mixed-Content] Le « https://www.inpact-hardware.com » d'origine a été chargé dans un contexte sécurisé et a chargé une ressource blocable en option image non sécurisée à « unsafe:data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%201024%201024%22%20style%3D%22background%3A%2362c464%22%3E%3Cg%3E%3Ctext%20text-anchor%3D%22middle%22%20dy%3D%22.35em%22%20x%3D%22512%22%20y%3D%22512%22%20fill%3D%22%23ffffff%22%20font-size%3D%22700%22%20font-family%3D%22-apple-system%2C%20BlinkMacSystemFont%2C%20Roboto%2C%20Helvetica%2C%20Arial%2C%20sans-serif%22%3EB%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fsvg%3E ».

SEC7137: [Mixed-Content] Le « https://www.inpact-hardware.com » d'origine a été chargé dans un contexte sécurisé et a chargé une ressource blocable en option image non sécurisée à « unsafe:data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%201024%201024%22%20style%3D%22background%3A%236a62c4%22%3E%3Cg%3E%3Ctext%20text-anchor%3D%22middle%22%20dy%3D%22.35em%22%20x%3D%22512%22%20y%3D%22512%22%20fill%3D%22%23ffffff%22%20font-size%3D%22700%22%20font-family%3D%22-apple-system%2C%20BlinkMacSystemFont%2C%20Roboto%2C%20Helvetica%2C%20Arial%2C%20sans-serif%22%3EI%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fsvg%3E ».`

Habituellement, je passe par la PWA donc je n'ai pas de console pour voir s'il y a des erreurs (ou alors il faudrait que je la démarre en mode debug !).
