### ISSUE TITLE
Affichage incorrect sous Windows 10 Mobile

### ISSUE THREAD

**Issue by Aarklendoia** [NextINpact/InpactHardware#7]
L'affichage est décalé sous Windows 10 Mobile. En effet, l'avatar se retrouve à la ligne à gauche sous le titre, rendant le site difficilement utilisable.

**Comment by pehadavid** [comment]
Hello,

On ne supporte pas officiellement Win10 mobile, mais on peut-être faire quelque chose : du coup sur quel device ?

**Comment by Aarklendoia** [comment]
Sur un 950XL. Je pense simplement que le logo IH est juste trop grand et que ça fait tout revenir à la ligne. Dans la PWA que j’ai faite pour IH (je t’ai laissé des messages sur Discord à ce propos), si je réduis la fenêtre à la taille limité autorisée (qui normalement correspond à l’affichage sur smartphone), je n’ai plus le problème, mais il a existé.

Si tu veux continuer à discuter, je suis sur Skype et Discord !

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Pierre-Alain David <notifications@github.com>
Envoyé : Monday, March 18, 2019 1:53:33 PM
À : NextINpact/InpactHardware
Cc : Aarklendoia; Author
Objet : Re: [NextINpact/InpactHardware] Affichage incorrect sous Windows 10 Mobile (#7)


Hello,

On ne supporte pas officiellement Win10 mobile, mais on peut-être faire quelque chose : du coup sur quel device ?

**Comment by pehadavid** [comment]
@BenjaminINpact tu peux regarder ? merci :)

**Comment by BenjaminINpact** [comment]
Hello, 
Pas de soucis ;)  en revanche serait-il possible d'avoir un screenshot? je ne reproduis pas le phénomène. 
On parle bien de l'avatar dans le header ?

**Comment by Aarklendoia** [comment]
Voilà !

Envoyé de mon appareil Windows 10

________________________________
De : BenjaminINpact <notifications@github.com>
Envoyé : Monday, March 18, 2019 2:42:33 PM
À : NextINpact/InpactHardware
Cc : Aarklendoia; Author
Objet : Re: [NextINpact/InpactHardware] Affichage incorrect sous Windows 10 Mobile (#7)


Hello,
Pas de soucis ;) en revanche serait-il possible d'avoir un screenshot? je ne reproduis pas le phénomène.
On parle bien de l'avatar dans le header ?

**Comment by BenjaminINpact** [comment]
La pièce jointe n'est pas là ^^

**Comment by Aarklendoia** [comment]
[cid:image004.png@01D4DD9F.38421360]


Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10


De : BenjaminINpact <notifications@github.com>
Envoyé : Monday, March 18, 2019 3:16:25 PM
À : NextINpact/InpactHardware
Cc : Aarklendoia; Author
Objet : Re: [NextINpact/InpactHardware] Affichage incorrect sous Windows 10 Mobile (#7)


La pièce jointe n'est pas là ^^

**Comment by Aarklendoia** [comment]
![IH Windows 10 Mobile](https://user-images.githubusercontent.com/1765298/54538857-5b2ad800-4995-11e9-9acd-26026cede4c6.png)

**Comment by Aarklendoia** [comment]
Il y a du mieux. La barre de titre est maintenant sur une seule ligne mais la recherche passe par-dessus et le rend donc complètement inaccessible.
