### ISSUE TITLE
Déconnexions régulières de IH

### ISSUE THREAD

**Issue by trou** [NextINpact/InpactHardware#8]
Bonjour,
je suis _souvent_ déconnecté de mon compte sur inpact-hardware, sans vraiment de raison. Je n'ai pas ce problème sur NI.

Malheureusement je n'ai pas vraiment d'information supplémentaire à fournir (à part que je suis sous Chrome)

**Comment by pehadavid** [comment]
Plusieurs correctifs ont été apporté, les sessions sont désormais valables 30 jours avec expiration glissante.
